import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { tap, catchError } from 'rxjs/operators';
import { EMPTY } from 'rxjs';
import { AuthFacade } from '@silver/tabata/auth';
import { ToastService } from '@silver/tabata/helpers';
import { WorkoutEditorFacade, WorkoutEditorService, type CreateWorkoutPayload, type UpdateWorkoutPayload } from '@silver/tabata/states/workout-editor';
import type { TabataWorkout } from '@silver/tabata/states/workouts';

const DATE_FORMAT = (d: Date): string => {
    const y = d.getFullYear();
    const M = String(d.getMonth() + 1).padStart(2, '0');
    const D = String(d.getDate()).padStart(2, '0');
    const h = String(d.getHours()).padStart(2, '0');
    const m = String(d.getMinutes()).padStart(2, '0');
    const s = String(d.getSeconds()).padStart(2, '0');
    return `${y}-${M}-${D}-${h}:${m}:${s}`;
};

function totalDurationMinutesFromDraft(draft: Partial<TabataWorkout>): number {
    const warmupSeconds = draft.warmup?.totalDurationSeconds ?? 0;
    const cooldownSeconds = draft.cooldown?.totalDurationSeconds ?? 0;
    const blocks = draft.blocks ?? [];
    const blocksSeconds = blocks.reduce((sum, block) => {
        const roundTotal = block.rounds * (block.workDurationSeconds + block.restDurationSeconds);
        return sum + roundTotal + (block.interBlockRestSeconds ?? 0);
    }, 0);
    const totalSeconds = warmupSeconds + blocksSeconds + cooldownSeconds;
    return Math.round(totalSeconds / 60);
}

const ALPHANUMERIC = 'abcdefghijklmnopqrstuvwxyz0123456789';
/** Generate workout id on the frontend; backend is not a full REST API and does not assign ids. */
function generateWorkoutId(): string {
    const randomPart = Array.from({ length: 6 }, () => ALPHANUMERIC[Math.floor(Math.random() * ALPHANUMERIC.length)]).join('');
    return `${Date.now()}${randomPart}`;
}

/** Returns human-readable labels for missing required fields (script excluded). */
function getMissingFieldLabels(draft: Partial<TabataWorkout>): string[] {
    const missing: string[] = [];
    if (draft.name == null || String(draft.name).trim() === '') missing.push('Name');
    if (draft.description == null || String(draft.description).trim() === '') missing.push('Description');
    if (draft.mainTargetBodypart == null || String(draft.mainTargetBodypart).trim() === '') missing.push('Main target body part');
    if (draft.secondaryTargetBodyparts != null && !Array.isArray(draft.secondaryTargetBodyparts)) missing.push('Secondary targets');
    if (draft.availableEquipments != null && !Array.isArray(draft.availableEquipments)) missing.push('Available equipment');
    if (draft.generatedByAi !== undefined && typeof draft.generatedByAi !== 'boolean') missing.push('Generated by AI');

    if (draft.warmup == null) {
        missing.push('Warmup');
    } else {
        if (draft.warmup.totalDurationSeconds == null || draft.warmup.totalDurationSeconds < 0) missing.push('Warmup duration');
        if (!Array.isArray(draft.warmup.movements)) missing.push('Warmup movements');
        else {
            const invalid = draft.warmup.movements.some((m) => !m?.exerciseId?.trim() || m.durationSeconds == null || m.durationSeconds < 0);
            if (invalid) missing.push('Warmup movements (each needs exercise and duration)');
        }
    }

    if (draft.cooldown == null) {
        missing.push('Cooldown');
    } else {
        if (draft.cooldown.totalDurationSeconds == null || draft.cooldown.totalDurationSeconds < 0) missing.push('Cooldown duration');
        if (!Array.isArray(draft.cooldown.movements)) missing.push('Cooldown movements');
        else {
            const invalid = draft.cooldown.movements.some((m) => !m?.exerciseId?.trim() || m.durationSeconds == null || m.durationSeconds < 0);
            if (invalid) missing.push('Cooldown movements (each needs exercise and duration)');
        }
    }

    if (!Array.isArray(draft.blocks) || draft.blocks.length === 0) {
        missing.push('Main workout blocks');
    } else {
        draft.blocks.forEach((block, i) => {
            if (
                block.rounds == null ||
                block.workDurationSeconds == null ||
                block.restDurationSeconds == null ||
                block.interBlockRestSeconds == null ||
                !block.exerciseId?.trim()
            ) {
                missing.push(`Block ${i + 1} (rounds, work/rest/inter-block duration, exercise)`);
            }
        });
    }

    return missing;
}

@Injectable({ providedIn: 'root' })
export class WorkoutSubmitService {
    private readonly authFacade = inject(AuthFacade);
    private readonly workoutEditorFacade = inject(WorkoutEditorFacade);
    private readonly workoutEditorService = inject(WorkoutEditorService);
    private readonly toast = inject(ToastService);

    /**
     * Builds payload from current draft with userId and timestamps, then creates or updates the workout
     * via the existing workout editor HTTP service and syncs the store. Returns an observable that
     * emits the saved workout on success.
     */
    submitWorkout(): Observable<TabataWorkout> {
        const userId = this.authFacade.user()?.uid ?? '';
        const now = DATE_FORMAT(new Date());
        const draft = this.workoutEditorFacade.workoutDraft();
        const isEditMode = this.workoutEditorFacade.isEditMode();
        const existingWorkout = this.workoutEditorFacade.workout();

        const missing = getMissingFieldLabels(draft);
        if (missing.length > 0) {
            this.toast.showError(`Missing: ${missing.join(', ')}`);
            return EMPTY;
        }

        this.workoutEditorFacade.startSave();

        if (isEditMode && existingWorkout?.id) {
            const payload: UpdateWorkoutPayload = {
                ...draft,
                totalDurationMinutes: totalDurationMinutesFromDraft(draft),
                updatedByUserId: userId,
                updatedAt: now
            };
            return this.workoutEditorService.updateWorkout(existingWorkout.id, payload).pipe(
                tap((workout) => this.workoutEditorFacade.setWorkoutFromResponse(workout)),
                catchError((err: Error) => {
                    this.workoutEditorFacade.setSaveError(err.message);
                    return EMPTY;
                })
            );
        }

        const merged = this.workoutEditorFacade.mergedWorkout() as Record<string, unknown>;
        const rest = Object.fromEntries(Object.entries(merged).filter(([key]) => key !== 'id'));
        const payload: CreateWorkoutPayload & { id: string; createdAt: string } = {
            ...rest,
            id: generateWorkoutId(),
            totalDurationMinutes: totalDurationMinutesFromDraft(this.workoutEditorFacade.workoutDraft()),
            createdByUserId: userId,
            updatedByUserId: userId,
            createdAt: now
        } as CreateWorkoutPayload & { id: string; createdAt: string };
        return this.workoutEditorService.createWorkout(payload).pipe(
            tap((workout) => this.workoutEditorFacade.setWorkoutFromResponse(workout)),
            catchError((err: Error) => {
                this.workoutEditorFacade.setSaveError(err.message);
                return EMPTY;
            })
        );
    }
}
