import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { tap, catchError } from 'rxjs/operators';
import { EMPTY } from 'rxjs';
import { AuthFacade } from '@silver/tabata/auth';
import { ToastService } from '@silver/tabata/helpers';
import { WorkoutEditorFacade, WorkoutEditorService, type CreateWorkoutPayload, type UpdateWorkoutPayload } from '@silver/tabata/states/workout-editor';
import type { TabataWorkout } from '@silver/tabata/states/workouts';

function totalDurationMinutesFromDraft(draft: Partial<TabataWorkout>): number {
    const warmupSeconds = draft.warmup?.totalDurationSeconds ?? 0;
    const cooldownSeconds = draft.cooldown?.totalDurationSeconds ?? 0;
    const blocks = draft.blocks ?? [];
    const blocksSeconds = blocks.reduce((sum, block) => {
        const roundTotal = block.rounds * (block.workDurationSeconds + block.restDurationSeconds);
        return sum + roundTotal + (block.interBlockRestSeconds ?? 0);
    }, 0);
    const totalSeconds = warmupSeconds + blocksSeconds + cooldownSeconds;
    return Math.round(totalSeconds / 60);
}

/** Returns human-readable labels for missing required fields (script excluded). */
export function getMissingFieldLabels(draft: Partial<TabataWorkout>): string[] {
    const missing: string[] = [];
    if (draft.name == null || String(draft.name).trim() === '') missing.push('Name');
    if (draft.description == null || String(draft.description).trim() === '') missing.push('Description');
    if (draft.mainTargetBodypart == null || String(draft.mainTargetBodypart).trim() === '') missing.push('Main target body part');
    if (draft.secondaryTargetBodyparts != null && !Array.isArray(draft.secondaryTargetBodyparts)) missing.push('Secondary targets');
    if (draft.availableEquipments != null && !Array.isArray(draft.availableEquipments)) missing.push('Available equipment');
    if (draft.generatedByAi !== undefined && typeof draft.generatedByAi !== 'boolean') missing.push('Generated by AI');

    if (draft.warmup == null) {
        missing.push('Warmup');
    } else {
        if (draft.warmup.totalDurationSeconds == null || draft.warmup.totalDurationSeconds < 0) missing.push('Warmup duration');
        if (!Array.isArray(draft.warmup.movements)) missing.push('Warmup movements');
        else {
            const invalid = draft.warmup.movements.some((m) => !m?.exerciseId?.trim() || m.durationSeconds == null || m.durationSeconds < 0);
            if (invalid) missing.push('Warmup movements (each needs exercise and duration)');
        }
    }

    if (draft.cooldown == null) {
        missing.push('Cooldown');
    } else {
        if (draft.cooldown.totalDurationSeconds == null || draft.cooldown.totalDurationSeconds < 0) missing.push('Cooldown duration');
        if (!Array.isArray(draft.cooldown.movements)) missing.push('Cooldown movements');
        else {
            const invalid = draft.cooldown.movements.some((m) => !m?.exerciseId?.trim() || m.durationSeconds == null || m.durationSeconds < 0);
            if (invalid) missing.push('Cooldown movements (each needs exercise and duration)');
        }
    }

    if (!Array.isArray(draft.blocks) || draft.blocks.length === 0) {
        missing.push('Main workout blocks');
    } else {
        draft.blocks.forEach((block, i) => {
            if (
                block.rounds == null ||
                block.workDurationSeconds == null ||
                block.restDurationSeconds == null ||
                block.interBlockRestSeconds == null ||
                !block.exerciseId?.trim()
            ) {
                missing.push(`Block ${i + 1} (rounds, work/rest/inter-block duration, exercise)`);
            }
        });
    }

    return missing;
}

@Injectable({ providedIn: 'root' })
export class WorkoutSubmitService {
    private readonly authFacade = inject(AuthFacade);
    private readonly workoutEditorFacade = inject(WorkoutEditorFacade);
    private readonly workoutEditorService = inject(WorkoutEditorService);
    private readonly toast = inject(ToastService);

    /**
     * Builds payload from current draft and creates or updates the workout via the API.
     * API assigns id, createdAt, and updatedAt. Returns an observable that emits the saved workout on success.
     */
    submitWorkout(): Observable<TabataWorkout> {
        const userId = this.authFacade.user()?.uid ?? '';
        const draft = this.workoutEditorFacade.workoutDraft();
        const isEditMode = this.workoutEditorFacade.isEditMode();
        const existingWorkout = this.workoutEditorFacade.workout();

        const missing = getMissingFieldLabels(draft);
        if (missing.length > 0) {
            this.toast.showError(`Missing: ${missing.join(', ')}`);
            return EMPTY;
        }

        this.workoutEditorFacade.startSave();

        if (isEditMode && existingWorkout?.id) {
            const draftObj = draft as Record<string, unknown>;
            const rest = Object.fromEntries(Object.entries(draftObj).filter(([k]) => k !== 'updatedAt'));
            const payload: UpdateWorkoutPayload = {
                ...rest,
                totalDurationMinutes: totalDurationMinutesFromDraft(draft),
                updatedByUserId: userId
            };
            return this.workoutEditorService.updateWorkout(existingWorkout.id, payload).pipe(
                tap((workout) => {
                    this.workoutEditorFacade.setWorkoutFromResponse(workout);
                    this.toast.showSuccess('Workout updated');
                }),
                catchError((err: Error) => {
                    this.workoutEditorFacade.setSaveError(err.message);
                    this.toast.showError(err.message || 'Failed to update workout');
                    return EMPTY;
                })
            );
        }

        const merged = this.workoutEditorFacade.mergedWorkout() as Record<string, unknown>;
        const rest = Object.fromEntries(Object.entries(merged).filter(([k]) => k !== 'id' && k !== 'createdAt' && k !== 'updatedAt'));
        const payload: CreateWorkoutPayload = {
            ...rest,
            totalDurationMinutes: totalDurationMinutesFromDraft(this.workoutEditorFacade.workoutDraft()),
            createdByUserId: userId,
            updatedByUserId: userId
        } as CreateWorkoutPayload;
        return this.workoutEditorService.createWorkout(payload).pipe(
            tap((workout) => {
                this.workoutEditorFacade.setWorkoutFromResponse(workout);
                this.toast.showSuccess('Workout created');
            }),
            catchError((err: Error) => {
                this.workoutEditorFacade.setSaveError(err.message);
                this.toast.showError(err.message || 'Failed to create workout');
                return EMPTY;
            })
        );
    }

    /**
     * Returns true when the current draft is complete enough to be saved.
     * Useful for autosave in edit mode.
     */
    canSubmitWorkout(): boolean {
        const draft = this.workoutEditorFacade.workoutDraft();
        return getMissingFieldLabels(draft).length === 0;
    }

    /**
     * Schedules a single autosave after a short delay when conditions are met.
     * Call from an effect; return the result as the effect cleanup.
     * @param hasUnsaved Whether the draft has unsaved changes
     * @param isEditMode Whether we are editing an existing workout
     * @param notBusy Whether the editor is not loading/saving
     * @param canSubmit Whether the draft is complete enough to submit
     * @returns Cleanup function to clear the timer, or undefined
     */
    scheduleAutosaveWhen(
        hasUnsaved: boolean,
        isEditMode: boolean,
        notBusy: boolean,
        canSubmit: boolean
    ): (() => void) | undefined {
        if (!hasUnsaved || !isEditMode || !notBusy || !canSubmit) return undefined;
        const id = setTimeout(() => this.submitWorkout().subscribe(), 800);
        return () => clearTimeout(id);
    }
}
